// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";


//Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";


//Comm
export const UPDATE_COMM = "UPDATE_COMM";
export const UPDATE_COMM_SUCCESS = "UPDATE_COMM_SUCCESS";
export const UPDATE_COMM_FAILURE = "UPDATE_COMM_FAILURE";

export const SHOW_COMM = "SHOW_COMM";
export const SHOW_COMM_SUCCESS = "SHOW_COMM_SUCCESS";
export const SHOW_COMM_FAILURE = "SHOW_COMM_FAILURE";




